version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - gocritic
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unused
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: exported
        - name: error-return
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sudores/twt-test-task
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
